config/routes.rb
require 'sidekiq/web'

CrmSoftwearcrmCom::Application.routes.draw do
  mount ActsAsWarnable::Engine => '/'

  root 'home#index'
  get 'home/api_warnings', to: 'home#api_warnings', as: :api_warnings
  get 'home/not_allowed', to: 'home#not_allowed', as: :not_allowed

  get 'imprints/ink_colors', to: 'imprints#ink_colors', as: :imprint_ink_colors
  get 'imprints/new', to: 'imprints#new', as: :new_imprint
  get  'jobs/:job_id/imprints/from_quotes', to: 'imprints#from_quotes', as: :imprint_from_quotes
  post 'jobs/:job_id/imprints/from_quotes', to: 'imprints#create_from_quotes'

  resources :imprintables do
    collection do
      resources :brands, :colors
      resources :imprintable_groups
      post 'update_imprintable_variants'
      get 'costs', to: 'costs#mass_new'
      post 'costs', to: 'costs#mass_create'

      resources :sizes do
        collection do
          post 'update_size_order'
        end
      end
    end
  end

  resources :user_attributes, only: [:edit, :update]
  get '/set-session-token', to: 'users#set_session_token', as: :set_session_token
  get '/clear-user-query-cache', to: 'users#clear_query_cache', as: :clear_user_query_cache

  get 'tags/:tag', to: 'imprintables#index', as: :tag

  resources :brands, :colors, :costs
  resources :artworks do
    collection do
      get 'select'
    end
    member do
      get 'full_view'
    end
  end

  resources :artwork_requests do
    member do
      post 'transition(/:state_machine(/:transition))' => :state, as: :transition
    end
    collection do
      get 'tab/:tab' => :tab, as: :tab
    end
  end

  get 'proofing_manager_dashboard', to: 'artwork_requests#manager_dashboard', as: :proofing_manager_dashboard

  resources :prices, only: [:create, :new, :destroy, :index] do
    collection do
      get 'destroy_all'
    end
  end

  resources :quotes, shallow: true do
    member do
      put 'integrate', to: 'quotes#integrate'
    end
    resource :emails

    resources :comments

    collection do
      get 'quote_select'
      post 'stage_quote'
    end
  end
  post 'email/freshdesk', to: 'emails#freshdesk'
  resources :comments
  warning_paths_for :quotes, :orders

  resources :quote_requests do
    get :dock
    post :create_freshdesk_ticket
    resources :emails, :comments

    collection do
      post :filter
    end
  end
  warning_paths_for :quote_requests
  resources :warnings

  scope 'configuration' do
    resources :shipping_methods, :stores, :line_item_templates
    resources :imprint_methods do
      get '/print_locations', to: 'imprint_methods#print_locations', as: :print_locations
    end
    match 'integrated_crms', to: 'settings#edit', via: :get
    match 'update_integrated_crms', to: 'settings#update', via: :put
    resources :email_templates do
      get '/preview_body', to: 'email_templates#preview_body', as: :preview_body
      collection do
        # TODO: you'll need something like this if you want to expand templates to use more than just quotes
        get '/fetch_table_attributes/(:table_name)', to: 'email_templates#fetch_table_attributes'
      end
    end
    resources :platen_hoops
  end

  scope 'administration' do
    resources :coupons do
      collection { get '/validate/:code', to: 'coupons#validate', as: :validate_coupon }
    end
    resources :in_store_credits do
      collection { get :search }
    end
    resources :payment_drops, except: :destroy
    resources :deposits
  end

  get 'payments/undropped', to: 'payments#undropped'
  resources :payments, :shipments

  resources :orders do
    member do
      get 'tab/:tab' => :tab, as: :tab
      get 'production_dashboard', as: 'production_dashboard'
      get :imprintable_sheets, as: :imprintable_sheets
      get :order_report, as: :order_report
      get 'state/:state_machine' => :state,  as: :state
      get :check_cancelation
      post 'transition/(:state_machine/:transition)' => :state, as: :transition
      post :send_to_production
      post :clone
    end

    resources :comments

    collection do
      get 'fba'
      get 'new_fba'
      post 'fba_job_info'
    end

    get 'timeline', to: 'timeline#show', as: :timeline
    resources :payments, :discounts, shallow: true
    resources :artwork_requests
    resources :proofs do
      member do
        post 'transition/(:state_machine/:transition)' => :state, as: :transition
      end

      collection do
        get 'email_customer'
        post 'email_customer'
      end
    end

    resources :jobs, only: [:create, :update, :destroy, :show], shallow: true do
      resources :name_numbers, only: [:create, :destroy]
      member do
        get 'names_numbers', as: :name_number_csv_from
        put :duplicate
      end

      resources :line_items, except: [:update] do
        get :form_partial, on: :member
        post :update_sort_orders
      end
      resources :imprints, except: [:index]
    end
  end

  resources :fba_spreadsheet_uploads
  resources :fba_job_templates do
    collection do
      get :print_locations
    end
  end
  resources :fba_products do
    collection do
      get :variant_fields
      get :new_from_spreadsheet
      post :upload_spreadsheet
    end
  end

  post   'line_items', to: 'line_items#create'
  post   'jobs/:job_id/line_items/from_quotes', to: 'line_items#create_from_quotes', as: :line_items_from_quote
  get    'line_item/select_options', to: 'line_items#select_options'
  put    'line_items/update', to: 'line_items#update'
  patch  'line_items/update', to: 'line_items#update'

  put    'jobs/:job_id/imprints/update', to: 'imprints#update', as: :job_imprints_update
  patch  'jobs/:job_id/imprints/update', to: 'imprints#update'

  namespace 'search' do
    resources :queries
  end

  get '/search', to: 'search/queries#search', as: :search

  resources :sales_reports, only: [:index, :create]
  get '/sales_reports/:report_type/:start_time...:end_time(.:format)', to: 'sales_reports#show', as: :sales_reports_show

  namespace 'api', defaults: { format: :json } do
    match '*path', to: 'api#options', via: :options
    resources 'orders', only: [:index, :show, :update]
    resources 'jobs', only: [:index, :show, :update]
    resources 'imprints', only: [:index, :show, :update]
    resources 'imprintables'
    resources 'imprintable_variants', only: [:index, :show]
    resources 'colors'
    resources 'sizes'
    resources 'quote_requests', only: [:create, :index, :show]
    resources 'shipments', only: [:index, :show, :update]
  end

  mount Sidekiq::Web => '/sidekiq'

  get '/undock', to: 'home#undock'
  get '/undock/:quote_request_id', to: 'home#undock'

  post '/error-report', to: 'error_reports#email_report'

  namespace 'customer' do
    resources :orders, only: [:show, :edit, :update] do
      resources :payments, only: [:index, :new, :create] do
        collection do
          match 'paypal_express', via: [:get, :post]
          match 'paypal_express_success', via: [:get, :post]
        end
      end
    end
  end

  namespace 'crm' do
    resources :contacts
  end

end

app/models/quote_request.rb
class QuoteRequest < ActiveRecord::Base
  include TrackingHelpers
  include IntegratedCrms
  include Softwear::Auth::BelongsToUser

  tracked by_current_user + { parameters: { s: ->(_c, r) { r.track_state_changes } } }
  acts_as_warnable
  acts_as_commentable

  get_insightly_api_key_from { Setting.insightly_api_key }

  scope :of_interest, -> { where.not status: 'could_not_quote' }
  scope :assigned, -> { where status: 'assigned' }
  scope :unassigned, -> { where.not status: 'assigned' }
  default_scope { order('quote_requests.created_at DESC') }

  paginates_per 50

  searchable do
    text :name, :email, :description, :source, :status
    text :salesperson do
      salesperson.try(:name)
    end
    integer :salesperson_id
    integer :id

    string :status
    time :created_at
  end

  QUOTE_REQUEST_STATUSES = %w(
    assigned pending quoted requested_info could_not_quote
    referred_to_design_studio duplicate
  )

  belongs_to_user_called :salesperson
  has_many :quote_request_quotes
  has_many :quotes, through: :quote_request_quotes
  has_many :orders, through: :quotes
  has_many :emails, as: :emailable, dependent: :destroy
  has_many :customer_uploads, dependent: :destroy
  has_many :quote_request_imprintables, dependent: :destroy
  has_many :imprintables, through: :quote_request_imprintables

  accepts_nested_attributes_for :customer_uploads

  validates :name, :email, :description, :source, presence: true
  validates :reason, presence: true, if: :reason_needed?

  before_validation(on: :create) { self.status = 'pending' if status.nil? }
  before_create :enqueue_link_integrated_crm_contacts
  before_save :notify_salesperson_if_assigned
  before_save { self.status = 'assigned' if salesperson_id_changed? && salesperson_id_was.nil? }

  def send_assigned_email(user_id)
    return if user_id != salesperson_id || salesperson_id.nil?
    QuoteRequestMailer.notify_salesperson_of_quote_request_assignment(self).deliver
  end

  def imprintable_quantities
    Hash[
      quote_request_imprintables.map do |qri|
        [qri.imprintable_id, qri.quantity]
      end
    ]
  end

  def imprintable_quantities=(value)
    return if value.blank?
    if value.is_a?(String)
      hash = JSON.parse(value.gsub('&quot;', '"'))
    elsif value.is_a?(Hash)
      hash = value
    else
      raise "Expected hash or string for QuoteRequest#imprintable_quantities=, got #{value.inspect}"
    end

    hash.each do |imprintable_id, quantity|
      next if quantity.to_i == 0

      quote_request_imprintables.build(
        imprintable_id: imprintable_id,
        quantity:       quantity.to_i
      )
    end
  end

  def assigned?
    status == 'assigned'
  end
  def unassigned?
    status != 'assigned'
  end

  def others_with_same_status
    QuoteRequest.where(salesperson_id: salesperson_id)
  end
  def next
    @next ||= others_with_same_status.where('id < ?', id).order(id: :desc).first
  end
  def previous
    @previous ||= others_with_same_status.where('id > ?', id).order(id: :asc).first
  end

  def reason_needed?
    status == 'could_not_quote'
  end

  def status=(new_status)
    @old_status = status
    super(new_status)
  end

  def track_state_changes
    if status != @old_status
      {
        status_changed_from: @old_status,
        status_changed_to: status
      }
    else
      {}
    end
  end

  def insightly_contact_url
    return nil if insightly_contact_id.nil?
    "https://googleapps.insight.ly/Contacts/Details/#{insightly_contact_id}"
  end

  def freshdesk_contact_url
    return nil if freshdesk_contact_id.nil?
    "http://annarbortees.freshdesk.com/contacts/#{freshdesk_contact_id}"
  end

  def linked_with_insightly?
    !insightly_contact_id.nil?
  end

  def first_name
    /(?<first_name>^\w+)/ =~ name
    first_name
  end
  def last_name
    /(?<first_name>^\w+)\s+(?<last_name>.*)/ =~ name
    last_name
  end

  def activity_source(activity)
    "Quote Request" if activity.key.include?('create')
  end

  def link_with_insightly
    return if insightly.nil?

    contact = create_insightly_contact(self)
    if contact
      self.insightly_contact_id = contact.contact_id

      if contact.try(:links).respond_to?(:each)
        contact.links.each do |link|
          if link.key?('organisation_id')
            # TODO Supposed to query for organisation at this point!
            # Or something I actually have no idea.
            # self.organisation_id = link['organisation_id']
            break
          end
        end
      end

      logger.info "Set Quote Request Insightly contact to #{insightly_contact_id}"
    end
  end

  def link_with_freshdesk
    return if freshdesk.nil?
    begin
      user = JSON.parse(freshdesk.get_users(query: "email is #{email}"))
        .first
        .try(:[], 'user')

      if user.nil?
        if organization
          # NOTE Freshdesk calls them "companies" externally, and
          # "customers" internally. Awesome, right?
          comp = JSON.parse(freshdesk.get_companies(
              letter: organization.each_char.next
            ))
            .find { |c| c['customer']['name'].downcase == organization.downcase }

          comp ||= JSON.parse(freshdesk.post_companies(customer: {
              name: organization
            }))
            .try(:[], 'customer')

          freshdesk_company_id = comp.try(:[], 'id')
        end

        user = JSON.parse(freshdesk.post_users(user: {
          name: name,
          email: email,
          phone: format_phone(phone_number),
          customer_id: freshdesk_company_id
        }))
          .try(:[], 'user')
      end

      if user
        self.freshdesk_contact_id = user['id']
      end

    rescue Freshdesk::AlreadyExistedError => e
      logger.error "(QUOTE REQUEST - FRESHDESK) Error adding freshdesk contact"
      e
    rescue Freshdesk::ConnectionError => e
      logger.error "(QUOTE REQUEST - FRESHDESK) #{e.class}: #{e.message}"
      e
    rescue StandardError => e
      logger.error "(QUOTE REQUEST - FRESHDESK) #{e.class}: #{e.message}"
      e
    end
  end

  def create_freshdesk_ticket
    return if freshdesk.nil? || !freshdesk_ticket_id.blank?

    if freshdesk_contact_id.blank?
      requester_info = {
        name: name,
        email: email,
        phone: format_phone(phone_number)
      }
    else
      requester_info = {
        requester_id: freshdesk_contact_id
      }
    end

    ticket = JSON.parse(freshdesk.post_tickets(
        helpdesk_ticket: {
          source: 2,
          group_id: freshdesk_group_id(salesperson),
          ticket_type: 'Lead',
          subject: "Information regarding your quote request (##{id}) from the Ann Arbor T-shirt Company",
          description_html: freshdesk_description(self)
        }
          .merge(requester_info)
      ))
      .try(:[], 'helpdesk_ticket')

    self.freshdesk_ticket_id = ticket['display_id']
    save(validate: false)
    ticket
  end
  warn_on_failure_of :create_freshdesk_ticket, raise_anyway: true unless Rails.env.test?

  def linked_with_freshdesk?
    !freshdesk_contact_id.nil?
  end

  def to_dock
    %i(id name approx_quantity description date_needed)
      .map{|a| { a => self[a] } }
      .reduce({}, :merge)
  end

  def uploaded_file_urls
  end

  private

  def notify_salesperson_if_assigned
    self.send_assigned_email(salesperson_id) if salesperson_id_changed?
  end

  def enqueue_link_integrated_crm_contacts
    self.delay(queue: 'api').link_integrated_crm_contacts if should_access_third_parties?
  end
  warn_on_failure_of :enqueue_link_integrated_crm_contacts
  warn_on_failure_of :link_with_insightly
  warn_on_failure_of :link_with_freshdesk

  def link_integrated_crm_contacts
    link_with_insightly unless linked_with_insightly?
    link_with_freshdesk unless linked_with_freshdesk?
  end
end

app/controllers/api/quote_requests_controller.rb
module Api
  class QuoteRequestsController < Softwear::Lib::ApiController

    private

    def permitted_params
      params.permit(
        quote_request: [
          :name, :organization, :email, :date_needed, :description, :source,
          :phone_number, :approx_quantity, :domain, :ip_address, :imprintable_quantities,
          customer_uploads_attributes: [:filename, :url, :id]
        ]
      )
    end


  end
end

app/controllers/quote_requests_controller.rb
class QuoteRequestsController < InheritedResources::Base
  respond_to :json, :js

  before_action :set_current_action

  def index
    if session[:quote_request_status]
      set_quote_requests_of_status(session[:quote_request_status])
    else
      @quote_requests = QuoteRequest.of_interest.page(params[:page])
    end
  end

  def filter
    if params[:quote_request_status].blank?
      session[:quote_request_status] = nil
      @quote_requests = QuoteRequest.of_interest.page(params[:page])
    else
      status = params[:quote_request_status]
      session[:quote_request_status] = status
      set_quote_requests_of_status(status)
    end
    respond_to(&:js)
  end

  def dock
    quote_request = QuoteRequest.find(params[:quote_request_id])
    unless session[:docked].is_a?(Array)
      session[:docked] = []
    end
    session[:docked] << quote_request.to_dock
    redirect_to root_path, notice: "Docked Quote Request #{quote_request.id}"
  end

  def create_freshdesk_ticket
    @quote_request = QuoteRequest.find(params[:quote_request_id])
    begin
      @quote_request.create_freshdesk_ticket
      flash[:success] = "Freshdesk ticket created!"
    rescue StandardError => e
      flash[:alert] = "Failed to create freshdesk ticket. See warning for details."
    end

    redirect_to quote_request_path(@quote_request)
  end

  private

  def permitted_params
    params.permit(
      :id, quote_request: [:status, :salesperson_id, :reason, :freshdesk_contact_id]
    )
  end

  def set_current_action
    @current_action = 'quote_requests'
  end

  def set_quote_requests_of_status(status)
    page = params[:page]
    desired_status = session[:quote_request_status]
    salesperson_id = params[:salesperson_id]

    @quote_requests = QuoteRequest.search do
      with :status, desired_status
      with :salesperson_id, salesperson_id unless salesperson_id.blank?
      paginate page: page.blank? ? 1 : page
      order_by :created_at, :desc
    end
      .results
  end
end

app/views/quote_requests/_quotes_form.html.erb
<%= form_for quote_request do |f| %>
  <%= f.select :quote_ids, [], {}, multiple: true, data: { values: quote_request.quotes.map { |q| { id: q.id, text: q.name } }.to_json } %>
  <%= f.submit class: 'btn btn-submit' %>
<% end %>

app/views/quote_requests/_search.html.erb
<%= search_form_for QuoteRequest do |s| %>
    <div class="row">
      <div class="col-sm-3">
        <%= s.select :status, QuoteRequest::QUOTE_REQUEST_STATUSES,
                     nil: 'Status...', id: 'quote_requests_search_filter' %>
      </div>

      <div class="col-sm-3">
        <%= s.fulltext id: 'js_search', placeholder: 'Keywords' %>
      </div>

      <div class="col-sm-2">
        <%= s.submit %>
      </div>

      <div class="col-sm-2">
        <%= link_to 'Clear', '#', class: 'btn btn-primary js-clear-btn' %>
      </div>
    </div>
<% end %>

app/views/quote_requests/_status_edit.html.erb
<%= form_for quote_request, remote: true do |f| %>

  <%= f.text_field :status %>

  <%= button_tag id: 'quote-request-submit' do %>
    <i class='fa fa-check'></i>
  <% end %>

  <% if local_assigns[:custom_cancel] %>
    <a href="#" id='cancel-quote-request-edit-button'>
      <i class='fa danger fa-times-circle'></i>
    </a>

  <% else %>

    <%= link_to quote_request_path(quote_request), id: 'cancel-change-status', title: 'Cancel', method: :get, remote: true do %>
      <i class='fa danger fa-times-circle'></i>
    <% end %>
  <% end %>

<% end %>

app/views/quote_requests/_status_show.html.erb
<em id='quote-request-status-text'><%= quote_request.status %></em>

<%= link_to edit_quote_request_path(quote_request), id: 'change-status', title: 'Edit', method: :get, remote: true do %>
  <i class='fa fa-edit'></i>
<% end %>

app/views/quote_requests/show.html.erb
<div class="page-heading animated fadeInDownBig row">
  <div class="pull-left">
    <h1>Quote Request from <%= @quote_request.name %></h1>
  </div>
  <div class='pull-right'>
    <%= link_to quote_requests_path, class: 'btn btn-primary' do  %>
        <i class="fa fa-arrow-circle-left"></i> Return to Quote Request List
    <% end %>
    <%= link_to quote_request_dock_path(@quote_request), class: 'btn btn-warning dock' do  %>
        <i class="fa fa-toggle-down"></i> Dock
    <% end %>
    <% if @quote_request.freshdesk_ticket_id.blank? && (@quote_request.quotes.empty? || @quote_request.quotes.pluck(:freshdesk_ticket_id).any?(&:blank?)) %>
      <%= link_to quote_request_create_freshdesk_ticket_path(@quote_request.id), method: :post, class: 'btn btn-success' do  %>
          <i class="softwear-icon-freshdesk-icon"></i> Create Freshdesk Ticket
      <% end %>
    <% end %>
    <%= link_to new_quote_path(name: @quote_request.name, email: @quote_request.email, quote_request_id: @quote_request.id), class: 'btn btn-success' do  %>
        <i class="fa fa-quote-left"></i> Create Quote
    <% end %>

    <% if @quote_request.warnings.any? %>
      <%= link_to quote_request_warnings_path(@quote_request.id), class: 'btn btn-warning' do %>
        <i class='fa fa-exclamation-triangle'></i> Warnings
        <%= "(#{@quote_request.warnings.active.size})" if @quote_request.warnings.active.any? %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="box-info full">
  <div class='user-profile-content'>

    <div class='row'>
      <%= profile_picture_of @quote_request.salesperson if @quote_request.salesperson %>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Quote Submitted At:</strong>
      </div>
      <div class='col-sm-10'>
        <%= value_time(@quote_request.created_at) %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Salesperson:</strong>
      </div>
      <div class='col-sm-10'>
        <%= editable @quote_request, :salesperson_id, type: :select, data: { source: User.all.map{ |x| { value: x.id, text: x.full_name  } } } %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Name:</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.name %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Email:</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.email %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Phone Number:</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.phone_number || 'n/a' %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Organization</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.organization || 'n/a' %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Status:</strong>
      </div>
      <div class='col-sm-10' id='quote-request-status'>
        <%= editable @quote_request, :status, type: :select, data: { source: QuoteRequest::QUOTE_REQUEST_STATUSES } %>
      </div>
    </div>

    <% if @quote_request.status == 'could_not_quote' %>
      <div id='quote-request-reason-div' class='row'>
        <div class='col-sm-2'>
          <strong>Reason:</strong>
        </div>
        <div class='col-sm-10' id='quote-request-reason'>
          <%= @quote_request.reason %>
        </div>
      </div>
    <% end %>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Approximate Quantity:</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.approx_quantity %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Date Needed:</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.date_needed.strftime("%F") rescue 'n/a' %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Source:</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.source %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Description:</strong>
      </div>
      <div class='col-sm-10'>
        <%= @quote_request.description %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-2'>
        <strong>Freshdesk Contact ID:</strong>
      </div>
      <div class='col-sm-10' id='quote-request-status'>
        <%= editable @quote_request, :freshdesk_contact_id, type: :text %>
      </div>
    </div>

    <% unless @quote_request.customer_uploads.empty? %>
      <div class='row'>
        <div class='col-sm-2'>
          <strong>Uploaded Files:</strong>
        </div>
        <div class='col-sm-10' id='quote-request-files'>
          <% @quote_request.customer_uploads.each do |upload| %>
            <%= link_to upload.filename, "http://#{upload.full_url}", target: :_blank %>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @quote_request.linked_with_insightly? %>
      <div class='row'>
        <div class='col-sm-2'>
          <%= link_to 'Insightly Contact', @quote_request.insightly_contact_url, target: '_blank' %>
        </div>
        <div class='col-sm-10'>
        </div>
      </div>
    <% end %>

    <% if @quote_request.linked_with_freshdesk? %>
      <div class='row'>
        <div class='col-sm-2'>
          <%= link_to 'Freshdesk Contact', @quote_request.freshdesk_contact_url, target: '_blank' %>
        </div>
        <div class='col-sm-10'>
        </div>
      </div>
    <% end %>

    <% unless @quote_request.freshdesk_ticket_id.blank? %>
      <div class='row'>
        <div class='col-sm-2'>
          <%= link_to @quote_request.freshdesk_ticket_link, class: '',
                      'data-action' => 'new', 'data-toggle' => 'tooltip', 'title' => 'Freshdesk Ticket', target: '_blank' do %>
              <i class="softwear-icon-freshdesk-icon"></i> Freshdesk Ticket
          <% end %>
        </div>
        <div class='col-sm-10'>
          <%= link_to 'Prepare for Freshdesk', new_quote_request_email_path(@quote_request, freshdesk: true) %>
        </div>
      </div>
    <% end %>

    <% unless @quote_request.quote_request_imprintables.blank? %>
      <div class='row'>
        <div class='col-sm-2'>
          <strong>Imprintables:</strong>
        </div>
        <div class='col-sm-10'>
          <% @quote_request.quote_request_imprintables.each do |qri| %>
            <% if qri.imprintable.nil? %>
              Unknown Imprintable
            <% else %>
              <%= link_to qri.imprintable.name, imprintable_path(qri.imprintable_id), remote: true, target: :_blank %>
            <% end  %>
            &times;<%= qri.quantity %>
            <br />
          <% end %>
        </div>
      </div>
    <% end %>


    <div class='row'>
      <div class='col-sm-2'><strong>Quotes:</strong></div>
    </div>

    <div id='quote-request-quote-stuff'>
      <% if @quote_request.quotes.any? %>
        <% @quote_request.quotes.find_each do |quote| %>
          <div class='indent-field'>
            <%= link_to quote.name, quote_path(quote) %>
          </div>
        <% end %>
      <% else %>
          None
      <% end %>
    </div>

  </div>

  <div class='row'>
    <div class='col-sm-8'>
      <strong>Comments:</strong>

      <ul id='comments-list'>
        <% @quote_request.comments.each do |comment| %>
          <%= render 'comments/basic', comment: comment %>
        <% end %>
      </ul>
    </div>
    <div class='col-sm-4'></div>
  </div>
  <div class='row' id='qr-notes'>
    <div class='col-sm-2'></div>
    <div class='col-sm-8'>


      <%= bootstrap_form_for [@quote_request, Comment.new], id: 'comment-form', remote: true do |f| %>
        <%= f.hidden_field :user_id, value: current_user.try(:id) %>
        <%= f.text_field :title, maxlength: 140 %>
        <%= f.text_area :comment, maxlength: 65500, label: 'Comment *' %>
        <%= f.submit 'Add Comment', class: 'btn btn-success' %>
      <% end %>
    </div>
    <div class='col-sm-2'></div>
  </div>
</div>

<% if @quote_request.unassigned? || @quote_request.salesperson_id == current_user.id %>
  <div class='row'>
    <div class='pull-left'>
      <% if @quote_request.previous %>
        <%= quote_request_button(@quote_request, :previous) %>
      <% end %>
    </div>
    <div class='pull-right'>
      <% if @quote_request.next %>
        <%= quote_request_button(@quote_request, :next) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/quote_requests/show.js.erb
$('#quote-request-status').html(
  "<%=j render 'status_show', quote_request: @quote_request %>"
);

app/views/quote_requests/update.js.erb
$('#quote-request-status').html(
  "<%=j render 'status_show', quote_request: @quote_request %>"
);

shine($('#quote-request-status-text'));