config/routes.rb
require 'sidekiq/web'

CrmSoftwearcrmCom::Application.routes.draw do
  mount ActsAsWarnable::Engine => '/'

  root 'home#index'
  get 'home/api_warnings', to: 'home#api_warnings', as: :api_warnings
  get 'home/not_allowed', to: 'home#not_allowed', as: :not_allowed

  get 'imprints/ink_colors', to: 'imprints#ink_colors', as: :imprint_ink_colors
  get 'imprints/new', to: 'imprints#new', as: :new_imprint
  get  'jobs/:job_id/imprints/from_quotes', to: 'imprints#from_quotes', as: :imprint_from_quotes
  post 'jobs/:job_id/imprints/from_quotes', to: 'imprints#create_from_quotes'

  resources :imprintables do
    collection do
      resources :brands, :colors
      resources :imprintable_groups
      post 'update_imprintable_variants'
      get 'costs', to: 'costs#mass_new'
      post 'costs', to: 'costs#mass_create'

      resources :sizes do
        collection do
          post 'update_size_order'
        end
      end
    end
  end

  resources :user_attributes, only: [:edit, :update]
  get '/set-session-token', to: 'users#set_session_token', as: :set_session_token
  get '/clear-user-query-cache', to: 'users#clear_query_cache', as: :clear_user_query_cache

  get 'tags/:tag', to: 'imprintables#index', as: :tag

  resources :brands, :colors, :costs
  resources :artworks do
    collection do
      get 'select'
    end
    member do
      get 'full_view'
    end
  end

  resources :artwork_requests do
    member do
      post 'transition(/:state_machine(/:transition))' => :state, as: :transition
    end
    collection do
      get 'tab/:tab' => :tab, as: :tab
    end
  end

  get 'proofing_manager_dashboard', to: 'artwork_requests#manager_dashboard', as: :proofing_manager_dashboard

  resources :prices, only: [:create, :new, :destroy, :index] do
    collection do
      get 'destroy_all'
    end
  end

  resources :quotes, shallow: true do
    member do
      put 'integrate', to: 'quotes#integrate'
    end
    resource :emails

    resources :comments

    collection do
      get 'quote_select'
      post 'stage_quote'
    end
  end
  post 'email/freshdesk', to: 'emails#freshdesk'
  resources :comments
  warning_paths_for :quotes, :orders

  resources :quote_requests do
    get :dock
    post :create_freshdesk_ticket
    resources :emails, :comments

    collection do
      post :filter
    end
  end
  warning_paths_for :quote_requests
  resources :warnings

  scope 'configuration' do
    resources :shipping_methods, :stores, :line_item_templates
    resources :imprint_methods do
      get '/print_locations', to: 'imprint_methods#print_locations', as: :print_locations
    end
    match 'integrated_crms', to: 'settings#edit', via: :get
    match 'update_integrated_crms', to: 'settings#update', via: :put
    resources :email_templates do
      get '/preview_body', to: 'email_templates#preview_body', as: :preview_body
      collection do
        # TODO: you'll need something like this if you want to expand templates to use more than just quotes
        get '/fetch_table_attributes/(:table_name)', to: 'email_templates#fetch_table_attributes'
      end
    end
    resources :platen_hoops
  end

  scope 'administration' do
    resources :coupons do
      collection { get '/validate/:code', to: 'coupons#validate', as: :validate_coupon }
    end
    resources :in_store_credits do
      collection { get :search }
    end
    resources :payment_drops, except: :destroy
    resources :deposits
  end

  get 'payments/undropped', to: 'payments#undropped'
  resources :payments, :shipments

  resources :orders do
    member do
      get 'tab/:tab' => :tab, as: :tab
      get 'production_dashboard', as: 'production_dashboard'
      get :imprintable_sheets, as: :imprintable_sheets
      get :order_report, as: :order_report
      get 'state/:state_machine' => :state,  as: :state
      get :check_cancelation
      post 'transition/(:state_machine/:transition)' => :state, as: :transition
      post :send_to_production
      post :clone
    end

    resources :comments

    collection do
      get 'fba'
      get 'new_fba'
      post 'fba_job_info'
    end

    get 'timeline', to: 'timeline#show', as: :timeline
    resources :payments, :discounts, shallow: true
    resources :artwork_requests
    resources :proofs do
      member do
        post 'transition/(:state_machine/:transition)' => :state, as: :transition
      end

      collection do
        get 'email_customer'
        post 'email_customer'
      end
    end

    resources :jobs, only: [:create, :update, :destroy, :show], shallow: true do
      resources :name_numbers, only: [:create, :destroy]
      member do
        get 'names_numbers', as: :name_number_csv_from
        put :duplicate
      end

      resources :line_items, except: [:update] do
        get :form_partial, on: :member
        post :update_sort_orders
      end
      resources :imprints, except: [:index]
    end
  end

  resources :fba_spreadsheet_uploads
  resources :fba_job_templates do
    collection do
      get :print_locations
    end
  end
  resources :fba_products do
    collection do
      get :variant_fields
      get :new_from_spreadsheet
      post :upload_spreadsheet
    end
  end

  post   'line_items', to: 'line_items#create'
  post   'jobs/:job_id/line_items/from_quotes', to: 'line_items#create_from_quotes', as: :line_items_from_quote
  get    'line_item/select_options', to: 'line_items#select_options'
  put    'line_items/update', to: 'line_items#update'
  patch  'line_items/update', to: 'line_items#update'

  put    'jobs/:job_id/imprints/update', to: 'imprints#update', as: :job_imprints_update
  patch  'jobs/:job_id/imprints/update', to: 'imprints#update'

  namespace 'search' do
    resources :queries
  end

  get '/search', to: 'search/queries#search', as: :search

  resources :sales_reports, only: [:index, :create]
  get '/sales_reports/:report_type/:start_time...:end_time(.:format)', to: 'sales_reports#show', as: :sales_reports_show

  namespace 'api', defaults: { format: :json } do
    match '*path', to: 'api#options', via: :options
    resources 'orders', only: [:index, :show, :update]
    resources 'jobs', only: [:index, :show, :update]
    resources 'imprints', only: [:index, :show, :update]
    resources 'imprintables'
    resources 'imprintable_variants', only: [:index, :show]
    resources 'colors'
    resources 'sizes'
    resources 'quote_requests', only: [:create, :index, :show]
    resources 'shipments', only: [:index, :show, :update]
  end

  mount Sidekiq::Web => '/sidekiq'

  get '/undock', to: 'home#undock'
  get '/undock/:quote_request_id', to: 'home#undock'

  post '/error-report', to: 'error_reports#email_report'

  namespace 'customer' do
    resources :orders, only: [:show, :edit, :update] do
      resources :payments, only: [:index, :new, :create] do
        collection do
          match 'paypal_express', via: [:get, :post]
          match 'paypal_express_success', via: [:get, :post]
        end
      end
    end
  end

  namespace 'crm' do
    resources :contacts
  end

end

app/models/fba_job_template.rb
class FbaJobTemplate < ActiveRecord::Base
  has_many :fba_imprint_templates, dependent: :destroy, inverse_of: :fba_job_template
  has_many :artworks, through: :fba_imprint_templates
  has_many :fba_skus, dependent: :destroy
  has_one :mockup, as: :assetable, class_name: 'Asset', dependent: :destroy

  accepts_nested_attributes_for :fba_imprint_templates, allow_destroy: true
  accepts_nested_attributes_for :mockup

  validates :name, presence: true, uniqueness: true

  scope :with_mockup, -> { where.not(mockup: nil) }
  scope :without_mockup, -> { where(mockup: nil) }

  searchable do
    text :name, :job_name
    string :name
    string :job_name
    boolean :needs_artwork
    boolean :needs_proof
    integer :imprint_count
    integer :id
  end

  def needs_artwork
    artworks.size < fba_imprint_templates.size
  end
  alias_method :needs_artwork?, :needs_artwork

  def needs_proof
    mockup.blank? || mockup.file.blank?
  end
  alias_method :needs_proof?, :needs_proof

  def job_name
    n = super
    n.blank? ? name : n
  end

  def mockup_attributes=(attrs)
    attrs = attrs.with_indifferent_access
    return if attrs[:file].blank?

    attrs[:description] = "FBA #{name} proof mockup"
    super(attrs)
  end

  def imprint_count
    fba_imprint_templates.size
  end

  def imprints_attributes
    hash = {}
    fba_imprint_templates.each_with_index do |imprint, index|
      hash[index] = {
        print_location_id: imprint.print_location_id,
        description:       imprint.description
      }
    end
    hash
  end

  private
end

app/controllers/fba_job_templates_controller.rb
class FbaJobTemplatesController < InheritedResources::Base
  include ActionView::Helpers::FormOptionsHelper

  def index
    @current_action = 'fba_job_templates#index'
    session[:fjt_needs_proof]   = params[:needs_proof]   if params[:needs_proof]
    session[:fjt_needs_artwork] = params[:needs_artwork] if params[:needs_artwork]

    art = filter_needs_artwork?
    proof = filter_needs_proof?
    if art || proof
      @fba_job_templates = FbaJobTemplate.search do
        if art && proof
          all_of do
            with :needs_artwork, true
            with :needs_proof,   true
          end
        elsif art
          with :needs_artwork, true
        elsif proof
          with :needs_proof,   true
        end

        paginate page: params[:page] || 1
      end
        .results
    else
      @fba_job_templates = FbaJobTemplate.page(params[:page])
    end
  end

  def show
    super do |format|
      format.html { redirect_to action: :edit }
      format.js
    end
  end

  def create
    super do |success, failure|
      success.html { redirect_to action: :index }
      failure.html { render }
    end
  end

  def print_locations
    return if params[:imprint_method_id].blank?

    @print_location_id_options = PrintLocation
      .where(imprint_method_id: params[:imprint_method_id])
      .map { |pl| { id: pl.id, text: pl.name } }
      .to_json
  end

  private

  def filter_needs_artwork?
    session[:fjt_needs_artwork] == '1'
  end
  def filter_needs_proof?
    session[:fjt_needs_proof] == '1'
  end

  def permitted_params
    params.permit(
      fba_job_template: [
        :name, :job_name,
        fba_imprint_templates_attributes: [
          :print_location_id, :description, :artwork_id,
          :id, :_destroy
        ],
        mockup_attributes: [
          :file, :id, :_destroy
        ]
      ]
    )
  end
end

app/views/fba_job_templates/_fba_imprint_template_fields.html.erb
<div class='imprint-entry col-sm-4'>
  <div class='box-info'>
    <div class='form-group'>
      <%= label_tag :imprint_method %>
      <%= select_tag :imprint_method, options_from_collection_for_select(ImprintMethod.all, :id, :name, f.object.imprint_method_id), include_blank: true, class: 'form-control imprint-method-select select2' %>
    </div>

    <div class='form-group'>
      <% print_locations = f.object.imprint_method.try(:print_locations) || [] %>

      <%= f.label :print_location_id %>
      <%= f.select :print_location_id, options_from_collection_for_select(print_locations, :id, :name, f.object.print_location_id), {}, class: 'form-control print-location-select select2' %>
    </div>

    <div class='form-group'>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  
    <div class='form-group artwork-target-container'>
      <div class='artwork-target' data-id='<%= f.object.id %>'>
        <% if f.object.artwork %>
          <% if f.object.artwork.is_image? %>
            <%= preview_artwork f.object.artwork, :thumb, alt: f.object.artwork.name, title: f.object.artwork.name, data: { toggle: 'tooltip' } %>
          <% else %>
            <%= image_tag '/assets/logo.png', size: "200x200" %>
            <%= content_tag :h6, "*No preview available" %>
          <% end %>
        <% end %>
        <%= f.hidden_field :artwork_id %>
      </div>
      <%= f.hidden_field :id, disabled: !f.object.persisted? %>
      <%= link_to 'Select Artwork', select_artworks_path, class: 'select-artwork' %>
    </div>

    <%= f.link_to_remove "Remove", class: 'btn btn-danger margin-topbot-10' %>
  </div>
</div>

app/views/fba_job_templates/_form.html.erb
<div class="box-info fba-job-template-form">
  <%= render partial: 'shared/modal_errors', locals: {object: fba_job_template} %>

  <%= nested_form_for fba_job_template do |f| %>
    <div id="horizontal-form" class="collapse in">
      <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10">
          <% if fba_job_template.errors.include?(:name) %>
            <% fba_job_template.errors.full_messages_for(:name).each do |message| %>
              <p class="text-danger"><%= message %></p>
            <% end %>
          <% end %>

          <%= f.text_field :name, class: 'form-control' %>

          <p class="help-block">Unique name for this job template</p>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :job_name, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10">
          <% if fba_job_template.errors.include?(:job_name) %>
            <% fba_job_template.errors.full_messages_for(:job_name).each do |message| %>
              <p class="text-danger"><%= message %></p>
            <% end %>
          <% end %>

          <%= f.text_field :job_name, class: 'form-control' %>

          <p class="help-block">Name to use in generated jobs</p>
        </div>
      </div>
    </div>

    <div class='form-group'>
      <%= f.label :fba_imprint_templates, 'Imprints' %>

      <div class='well'>

        <%= f.fields_for :fba_imprint_templates do |ff| %>
          <%= render 'fba_job_templates/fba_imprint_template_fields', f: ff %>
        <% end %>
        <%= f.link_to_add "Add Imprint", :fba_imprint_templates, class: 'btn btn-success' %>

        <div class="col-xs-12">
        </div>
        <div class='clearfix'></div>
      </div>
    </div>

    <div class='form-group'>
      <%= f.fields_for :mockup, fba_job_template.mockup || Asset.new do |ff| %>
        <div class='clearfix'></div>
        <%= ff.label :file, 'Mockup', class: 'control-label' %>
        <div class='clearfix'></div>

        <% if fba_job_template.errors.include?(:mockup) %>
          <% fba_job_template.errors.full_messages_for(:mockup).each do |message| %>
            <p class="text-danger"><%= message %></p>
          <% end %>
        <% end %>

        <% if fba_job_template.mockup.try(:file) %>
          <%= link_to fba_job_template.mockup.file.url, target: :_blank do %>
            <%= image_tag fba_job_template.mockup.file.url(:large) %>
          <% end %>
        <% end %>

        <%= ff.file_field :file, class: 'form-control' %>
      <% end %>
    </div>

    <%= f.submit "#{create_or_edit_text(@fba_job_template)} FBA Job Template", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/fba_job_templates/edit.html.erb
<div class="page-heading animated fadeInDownBig">
  <h1>FBA Job Template #<%= @fba_job_template.id %> <small>change name or imprints</small></h1>
</div>

<div class="row full">
  <%= render 'fba_job_templates/form', fba_job_template: @fba_job_template %>
</div>

app/views/fba_job_templates/index.html.erb
<div class="page-heading animated fadeInDownBig col-lg-9">
  <h1>FBA Job Templates</h1>
</div>
<div class="col-lg-2"></div>
<div class="col-lg-1">
  <%= link_to '+', new_fba_job_template_path, class: 'btn btn-success' %>
</div>

<%= search_form_for FbaJobTemplate, class: 'form-horizontal' do |s| %>
  <div class='form-group'>
    <%= s.fulltext placeholder: 'Search Terms', class: 'form-control' %>
  </div>
  <div class='col-sm-3'></div>
  <div class="col-sm-6">
    <%= s.submit class: 'btn-lg btn-block margin-top-10' %>
  </div>
  <div class='col-sm-3'></div>
<% end %>
<div class='clearfix'></div>

<%= form_tag fba_job_templates_url, method: :get do %>
<div class='well col-sm-2'>
  <div class='form-group'>
    <%= hidden_field_tag :needs_artwork, '0' %>
    <%= label_tag :needs_artwork %>
    <%= check_box_tag :needs_artwork, '1', session[:fjt_needs_artwork] == '1', class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= hidden_field_tag :needs_proof, '0' %>
    <%= label_tag :needs_proof %>
    <%= check_box_tag :needs_proof, '1', session[:fjt_needs_proof] == '1', class: 'form-control' %>
  </div>

  <%= button_tag 'Apply Filter', class: 'btn btn-default' %>
</div>
<% end %>

<%= paginate @fba_job_templates %>

<div class='box-info full clear'>
  <div class='table-responsive'>
    <table class='table table-hover table-striped'>
      <thead>
        <tr>
          <%= sorted_th :id, 'ID' %>
          <%= sorted_th :name, 'Unique Name' %>
          <%= sorted_th :job_name, 'Job Name' %>
          <%= sorted_th :imprint_count, 'Imprints' %>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @fba_job_templates.each do |fba_job_template| %>
          <tr>
            <td><%= fba_job_template.id %></td>
            <td><%= fba_job_template.name %></td>
            <td><%= fba_job_template.job_name %></td>
            <td>
              <span data-toggle='tooltip' title="<%= fba_job_template.fba_imprint_templates.map(&:name).join(', ') %>">
                <%= fba_job_template.fba_imprint_templates.size %>
              </span>
            </td>
            <td>
              <div class='btn-group btn-group-xs'>
                <%= link_to fa(:edit), edit_fba_job_template_path(fba_job_template), class: 'btn btn-sm btn-warning' %>
                <%= link_to fa('times-circle'), fba_job_template_path(fba_job_template), method: :delete, 'data-action' => 'destroy', class: 'btn btn-sm btn-danger', data: { confirm: %(Delete job template "#{fba_job_template.name}"?) } %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= paginate @fba_job_templates %>

app/views/fba_job_templates/new.html.erb
<div class="page-heading animated fadeInDownBig">
  <h1>New FBA Job Template <small>to alleviate manually adding jobs to FBA orders</small></h1>
</div>

<div class="row full">
  <%= render 'fba_job_templates/form', fba_job_template: @fba_job_template %>
</div>

app/views/fba_job_templates/print_locations.js.erb
$('.print-location-select option').remove();
$('.print-location-select').select2({
  data: <%= @print_location_id_options.html_safe %>
});