config/routes.rb
require 'sidekiq/web'

CrmSoftwearcrmCom::Application.routes.draw do
  mount ActsAsWarnable::Engine => '/'

  root 'home#index'
  get 'home/api_warnings', to: 'home#api_warnings', as: :api_warnings
  get 'home/not_allowed', to: 'home#not_allowed', as: :not_allowed

  get 'imprints/ink_colors', to: 'imprints#ink_colors', as: :imprint_ink_colors
  get 'imprints/new', to: 'imprints#new', as: :new_imprint
  get  'jobs/:job_id/imprints/from_quotes', to: 'imprints#from_quotes', as: :imprint_from_quotes
  post 'jobs/:job_id/imprints/from_quotes', to: 'imprints#create_from_quotes'

  resources :imprintables do
    collection do
      resources :brands, :colors
      resources :imprintable_groups
      post 'update_imprintable_variants'
      get 'costs', to: 'costs#mass_new'
      post 'costs', to: 'costs#mass_create'

      resources :sizes do
        collection do
          post 'update_size_order'
        end
      end
    end
  end

  resources :user_attributes, only: [:edit, :update]
  get '/set-session-token', to: 'users#set_session_token', as: :set_session_token
  get '/clear-user-query-cache', to: 'users#clear_query_cache', as: :clear_user_query_cache

  get 'tags/:tag', to: 'imprintables#index', as: :tag

  resources :brands, :colors, :costs
  resources :artworks do
    collection do
      get 'select'
    end
    member do
      get 'full_view'
    end
  end

  resources :artwork_requests do
    member do
      post 'transition(/:state_machine(/:transition))' => :state, as: :transition
    end
    collection do
      get 'tab/:tab' => :tab, as: :tab
    end
  end

  get 'proofing_manager_dashboard', to: 'artwork_requests#manager_dashboard', as: :proofing_manager_dashboard

  resources :prices, only: [:create, :new, :destroy, :index] do
    collection do
      get 'destroy_all'
    end
  end

  resources :quotes, shallow: true do
    member do
      put 'integrate', to: 'quotes#integrate'
    end
    resource :emails

    resources :comments

    collection do
      get 'quote_select'
      post 'stage_quote'
    end
  end
  post 'email/freshdesk', to: 'emails#freshdesk'
  resources :comments
  warning_paths_for :quotes, :orders

  resources :quote_requests do
    get :dock
    post :create_freshdesk_ticket
    resources :emails, :comments

    collection do
      post :filter
    end
  end
  warning_paths_for :quote_requests
  resources :warnings

  scope 'configuration' do
    resources :shipping_methods, :stores, :line_item_templates
    resources :imprint_methods do
      get '/print_locations', to: 'imprint_methods#print_locations', as: :print_locations
    end
    match 'integrated_crms', to: 'settings#edit', via: :get
    match 'update_integrated_crms', to: 'settings#update', via: :put
    resources :email_templates do
      get '/preview_body', to: 'email_templates#preview_body', as: :preview_body
      collection do
        # TODO: you'll need something like this if you want to expand templates to use more than just quotes
        get '/fetch_table_attributes/(:table_name)', to: 'email_templates#fetch_table_attributes'
      end
    end
    resources :platen_hoops
  end

  scope 'administration' do
    resources :coupons do
      collection { get '/validate/:code', to: 'coupons#validate', as: :validate_coupon }
    end
    resources :in_store_credits do
      collection { get :search }
    end
    resources :payment_drops, except: :destroy
    resources :deposits
  end

  get 'payments/undropped', to: 'payments#undropped'
  resources :payments, :shipments

  resources :orders do
    member do
      get 'tab/:tab' => :tab, as: :tab
      get 'production_dashboard', as: 'production_dashboard'
      get :imprintable_sheets, as: :imprintable_sheets
      get :order_report, as: :order_report
      get 'state/:state_machine' => :state,  as: :state
      get :check_cancelation
      post 'transition/(:state_machine/:transition)' => :state, as: :transition
      post :send_to_production
      post :clone
    end

    resources :comments

    collection do
      get 'fba'
      get 'new_fba'
      post 'fba_job_info'
    end

    get 'timeline', to: 'timeline#show', as: :timeline
    resources :payments, :discounts, shallow: true
    resources :artwork_requests
    resources :proofs do
      member do
        post 'transition/(:state_machine/:transition)' => :state, as: :transition
      end

      collection do
        get 'email_customer'
        post 'email_customer'
      end
    end

    resources :jobs, only: [:create, :update, :destroy, :show], shallow: true do
      resources :name_numbers, only: [:create, :destroy]
      member do
        get 'names_numbers', as: :name_number_csv_from
        put :duplicate
      end

      resources :line_items, except: [:update] do
        get :form_partial, on: :member
        post :update_sort_orders
      end
      resources :imprints, except: [:index]
    end
  end

  resources :fba_spreadsheet_uploads
  resources :fba_job_templates do
    collection do
      get :print_locations
    end
  end
  resources :fba_products do
    collection do
      get :variant_fields
      get :new_from_spreadsheet
      post :upload_spreadsheet
    end
  end

  post   'line_items', to: 'line_items#create'
  post   'jobs/:job_id/line_items/from_quotes', to: 'line_items#create_from_quotes', as: :line_items_from_quote
  get    'line_item/select_options', to: 'line_items#select_options'
  put    'line_items/update', to: 'line_items#update'
  patch  'line_items/update', to: 'line_items#update'

  put    'jobs/:job_id/imprints/update', to: 'imprints#update', as: :job_imprints_update
  patch  'jobs/:job_id/imprints/update', to: 'imprints#update'

  namespace 'search' do
    resources :queries
  end

  get '/search', to: 'search/queries#search', as: :search

  resources :sales_reports, only: [:index, :create]
  get '/sales_reports/:report_type/:start_time...:end_time(.:format)', to: 'sales_reports#show', as: :sales_reports_show

  namespace 'api', defaults: { format: :json } do
    match '*path', to: 'api#options', via: :options
    resources 'orders', only: [:index, :show, :update]
    resources 'jobs', only: [:index, :show, :update]
    resources 'imprints', only: [:index, :show, :update]
    resources 'imprintables'
    resources 'imprintable_variants', only: [:index, :show]
    resources 'colors'
    resources 'sizes'
    resources 'quote_requests', only: [:create, :index, :show]
    resources 'shipments', only: [:index, :show, :update]
  end

  mount Sidekiq::Web => '/sidekiq'

  get '/undock', to: 'home#undock'
  get '/undock/:quote_request_id', to: 'home#undock'

  post '/error-report', to: 'error_reports#email_report'

  namespace 'customer' do
    resources :orders, only: [:show, :edit, :update] do
      resources :payments, only: [:index, :new, :create] do
        collection do
          match 'paypal_express', via: [:get, :post]
          match 'paypal_express_success', via: [:get, :post]
        end
      end
    end
  end

  namespace 'crm' do
    resources :contacts
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @order_warnings = Order.search do
      with(:warnings_count).greater_than 0
      with(:salesperson_full_name,  current_user.full_name)
    end.results

    @rejected_artwork_requests = ArtworkRequest.search do
      with(:state, :artwork_request_rejected)
      with(:salesperson_full_name,  current_user.full_name)
    end.results
      .reject { |ar| ar.order.nil? }

    @pending_quote_requests = QuoteRequest.search do
      with(:status, 'assigned')
      with(:salesperson_id,  current_user.id)
    end.results
  end

  def undock
    if (@qr_id = params[:quote_request_id]) && session[:docked].is_a?(Array)
      session[:docked].delete_if { |qr| qr[:id].to_i == @qr_id.to_i }
    else
      session[:docked] = []
    end
  end

  def not_allowed
  end

  def api_warnings
    @api_warnings = Warning.active.where("message like 'API%'").page(params[:page] || 1)

    generate_api_warnings if params[:generate_api_warnings]
  end

  private

  def format_dates
    @starting = format_time(params[:start_date])
    @ending = format_time(params[:end_date])
  end

  def generate_api_warnings
    format_dates
    orders_in_production = Order.where("production_state = ? and updated_at > ? and updated_at < ?", :in_production, @starting, @ending)
    puts "Processing #{orders_in_production.count} orders"
    orders_in_production.each do |o|

      begin
        o.prod_api_confirm_job_counts
        o.prod_api_confirm_shipment
        o.prod_api_confirm_artwork_preprod

      rescue ActiveResource::ResourceNotFound => e
        message = "API Failed to find PRODUCTION(#{o.softwear_prod_id}) for CRM(#{o.id})"
        puts message

        o.warnings << Warning.new(
          source: 'API Production Configuration Report',
          message: message
        )

        Sunspot.index(o)
        next
      end

      o.jobs.each do |j|
        begin
#          j.prod_api_confirm_preproduction_trains
          j.prod_api_confirm_imprintable_train
        rescue ActiveResource::ResourceNotFound => e
          message = "API Failed to find PRODUCTION_JOB(#{j.softwear_prod_id}) for CRM_ORDER(#{o.id}) CRM_JOB(#{j.id})"
          puts message

          o.warnings << Warning.new(
            source: 'API Production Configuration Report',
            message: message
          )

          Sunspot.index(o)
          next
        end
      end
    end
  end

end

app/views/home/_chat_widget.html.erb
<!-- Chat widget -->
<div class="col-lg-6 box-info">
  <h2><strong>Chat</strong> Widget</h2>
  <!-- Additional button -->
  <div class="additional-btn">
    <a class="additional-icon" href="#fakelink"><i class="fa fa-refresh"></i></a>
    <a class="additional-icon" id="dropdownMenu4" data-toggle="dropdown">
      <i class="fa fa-cog"></i>
    </a>
    <ul class="dropdown-menu pull-right animated half fadeInDown" role="menu" aria-labelledby="dropdownMenu4">
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Action</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Another action</a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Something else here</a></li>
      <li role="presentation" class="divider"></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Separated link</a></li>
    </ul>
    <a class="additional-icon" href="#fakelink"><i class="fa fa-question-circle"></i></a>
  </div><!-- ENd div .addirional-btn -->
  <!-- Chat widget inner -->
  <div class="chat-widget">
    <ul class="media-list">
      <li class="media">
        <a class="pull-left" href="#fakelink">
          <%= image_tag 'avatar/1.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body warning">
          Hello, liquam ultricies malesuada feugiat?
          <p class="time">Just Now</p>
        </div>
      </li>
      <li class="media">
        <a class="pull-right" href="#fakelink">
          <%= image_tag 'avatar/5.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus
          <p class="time">A minute ago</p>
        </div>
      </li>
      <li class="media">
        <a class="pull-left" href="#fakelink">
          <%= image_tag 'avatar/2.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body danger">
          Cras sit amet erat sit amet lacus egestas placerat?
          <p class="time">23 minutes ago</p>
        </div>
      </li>
      <li class="media">
        <a class="pull-right" href="#fakelink">
          <%= image_tag 'avatar/5.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus
          <p class="time">2 hours ago</p>
        </div>
      </li>
      <li class="media">
        <a class="pull-left" href="#fakelink">
          <%= image_tag 'avatar/3.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body success">
          Hello, liquam ultricies malesuada feugiat?
          <p class="time">5 hours ago</p>
        </div>
      </li>
      <li class="media">
        <a class="pull-right" href="#fakelink">
          <%= image_tag 'avatar/5.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus
          <p class="time">Yesterday at 01:45 PM</p>
        </div>
      </li>
      <li class="media">
        <a class="pull-left" href="#fakelink">
          <%= image_tag 'avatar/4.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body info">
          Hello, liquam ultricies malesuada feugiat?
          <p class="time">2 days ago at 05:45 PM</p>
        </div>
      </li>
      <li class="media">
        <a class="pull-right" href="#fakelink">
          <%= image_tag 'avatar/5.jpg', class: 'media-object img-circle', alt: 'Avatar'%>
        </a>
        <div class="media-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus
          <p class="time">January 17, 2014 at 08:22 AM</p>
        </div>
      </li>
    </ul>
  </div><!-- End div .chat-widget -->
  <!-- Form chat -->
  <form role="form" class="input-chat">
    <input type="text" class="form-control input-lg" placeholder="Type and press Enter...">
  </form>
  <!-- End form chat -->
</div>
<!-- End chat widget -->

app/views/home/_info_box.html.erb
<!-- Begin info box -->
<div class="row">

  <!-- Visitor Info Box -->
  <div class="col-sm-3 col-xs-6">
    <!-- Box info -->
    <div class="box-info">
      <!-- Icon box -->
      <div class="icon-box">
								<span class="fa-stack">
								  <i class="fa fa-circle fa-stack-2x success"></i>
								  <i class="fa fa-flag fa-stack-1x fa-inverse"></i>
								</span>
      </div><!-- End div .icon-box -->
      <!-- Text box -->
      <div class="text-box">
        <h3>2,354</h3>
        <p>VISITORS</p>
      </div><!-- End div .text-box -->
      <div class="clear"></div>
      <!-- Progress bar -->
      <div class="progress progress-xs">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
          <span class="sr-only">80&#37; Complete</span>
        </div>
      </div><!-- End div .progress .progress-xs -->
      <p class="text-center">15&#37; Higher than Yesterday</p>
    </div><!-- End div .info-box -->
  </div>
  <!-- End Visitor Info Box -->


  <!-- Orders Info Box -->
  <div class="col-sm-3 col-xs-6">
    <!-- Box info -->
    <div class="box-info">
      <!-- Icon box -->
      <div class="icon-box">
								<span class="fa-stack">
								  <i class="fa fa-circle fa-stack-2x danger"></i>
								  <i class="fa fa-bell fa-stack-1x fa-inverse"></i>
								</span>
      </div><!-- End div .icon-box -->
      <!-- Text box -->
      <div class="text-box">
        <h3>1,234</h3>
        <p>ORDERS</p>
      </div><!-- End div .text-box -->
      <div class="clear"></div>
      <!-- Progress bar -->
      <div class="progress progress-xs">
        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
          <span class="sr-only">65&#37; Complete</span>
        </div>
      </div><!-- End div .progress .progress-xs -->
      <p class="text-center">5&#37; Higher than Yesterday</p>
    </div><!-- End div .info-box -->
  </div>
  <!-- End Orders Info Box -->


  <!-- Downloads Info Box -->
  <div class="col-sm-3 col-xs-6">
    <!-- Box info -->
    <div class="box-info">
      <!-- Icon box -->
      <div class="icon-box">
								<span class="fa-stack">
								  <i class="fa fa-circle fa-stack-2x info"></i>
								  <i class="fa fa-cloud-download fa-stack-1x fa-inverse"></i>
								</span>
      </div><!-- End div .icon-box -->
      <!-- Text box -->
      <div class="text-box">
        <h3>5,214</h3>
        <p>DOWNLOADS</p>
      </div><!-- End div .text-box -->
      <div class="clear"></div>
      <!-- Progress bar -->
      <div class="progress progress-xs">
        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%">
          <span class="sr-only">95&#37; Complete</span>
        </div>
      </div><!-- End div .progress .progress-xs -->
      <p class="text-center">12&#37; Higher than Yesterday</p>
    </div><!-- End div .info-box -->
  </div>
  <!-- End Downloads Info Box -->


  <!-- Shipping Info Box -->
  <div class="col-sm-3 col-xs-6">
    <!-- Box info -->
    <div class="box-info">
      <!-- Icon box -->
      <div class="icon-box">
								<span class="fa-stack">
								  <i class="fa fa-circle fa-stack-2x warning"></i>
								  <i class="fa fa-truck fa-stack-1x fa-inverse"></i>
								</span>
      </div><!-- End div .icon-box -->
      <!-- Text box -->
      <div class="text-box">
        <h3>572</h3>
        <p>SHIPPING</p>
      </div><!-- End div .text-box -->
      <div class="clear"></div>
      <!-- Progress bar -->
      <div class="progress progress-xs">
        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100" style="width: 55%">
          <span class="sr-only">55&#37; Complete</span>
        </div>
      </div><!-- End div .progress .progress-xs -->
      <p class="text-center">3&#37; Higher than Yesterday</p>
    </div><!-- End div .info-box -->
  </div>
  <!-- End Shipping Info Box -->

</div>
<!-- End of info box -->

app/views/home/_sales_report.html.erb
<div class="row">
  <div class="col-md-8">
    <!-- Sales report -->
    <div class="box-info full">
      <h2><strong>Sales</strong> Report</h2>

      <!-- Additional buttons -->
      <div class="additional-btn">
        <a class="additional-icon" href="#fakelink"><i class="fa fa-refresh"></i></a>
        <a class="additional-icon" id="dropdownMenu2" data-toggle="dropdown">
          <i class="fa fa-cog"></i>
        </a>
        <ul class="dropdown-menu pull-right animated half fadeInDown" role="menu" aria-labelledby="dropdownMenu2">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Action</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Another action</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Something else here</a></li>
          <li role="presentation" class="divider"></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#fakelink">Separated link</a></li>
        </ul>
        <a class="additional-icon" href="#fakelink" data-toggle="collapse" data-target="#sales-report"><i class="fa fa-chevron-down"></i></a>
        <a class="additional-icon" href="#fakelink"><i class="fa fa-question-circle"></i></a>
      </div><!-- End div .additional-button -->

      <!-- Sales report collapse body -->
      <div id="sales-report" class="collapse in">
        <div class="table-responsive">
          <table data-sortable class="table table-striped">
            <thead>
            <tr><th>No</th><th data-sortable="false"><input type="checkbox" id="select-all-rows"></th><th>Order ID</th><th>Buyer</th><th>Status</th><th>Location</th><th>Total</th></tr>
            </thead>
            <tbody>
            <tr><td>1</td><td><input type="checkbox" class="rows-check"></td><td>#0021</td><td><a href="#fakelink">John Doe</a></td><td><span class="label label-primary">Order</span></td><td>Yogyakarta, ID</td><td><strong class="text-primary">&#36; 1,245</strong></td></tr>
            <tr><td>2</td><td><input type="checkbox" class="rows-check"></td><td>#0022</td><td><a href="#fakelink">Johnny Depp</a></td><td><span class="label label-success">Payment</span></td><td>London, UK</td><td><strong class="text-success">&#36; 1,245</strong></td></tr>
            <tr><td>3</td><td><input type="checkbox" class="rows-check"></td><td>#0023</td><td><a href="#fakelink">Annisa Rusmanovski</a></td><td><span class="label label-success">Payment</span></td><td>Canbera, AU</td><td><strong class="text-success">&#36; 1,245</strong></td></tr>
            <tr><td>4</td><td><input type="checkbox" class="rows-check"></td><td>#0024</td><td><a href="#fakelink">Hana Sartika</a></td><td><span class="label label-danger">Cancel</span></td><td>Bali, ID</td><td><strong class="text-danger">&#36; 1,245</strong></td></tr>
            <tr><td>5</td><td><input type="checkbox" class="rows-check"></td><td>#0025</td><td><a href="#fakelink">Ari Rusmanto</a></td><td><span class="label label-primary">Order</span></td><td>Bandung, ID</td><td><strong class="text-primary">&#36; 1,245</strong></td></tr>
            <tr><td>6</td><td><input type="checkbox" class="rows-check"></td><td>#0026</td><td><a href="#fakelink">Willy Wonka</a></td><td><span class="label label-danger">Cancel</span></td><td>Semarang, ID</td><td><strong class="text-danger">&#36; 1,245</strong></td></tr>
            <tr><td>7</td><td><input type="checkbox" class="rows-check"></td><td>#0027</td><td><a href="#fakelink">Mohammed Sujiono</a></td><td><span class="label label-warning">Waiting</span></td><td>New York, US</td><td><strong class="text-warning">&#36; 1,245</strong></td></tr>
            <tr><td>8</td><td><input type="checkbox" class="rows-check"></td><td>#0028</td><td><a href="#fakelink">Jenny Doe</a></td><td><span class="label label-primary">Order</span></td><td>Boston, US</td><td><strong class="text-primary">&#36; 1,245</strong></td></tr>
            </tbody>
          </table>
        </div>
      </div><!-- End div #sales-report -->
    </div>
    <!-- End sales report -->

app/views/home/_timeline.html.erb
<div class="col-md-6 box-info">
  <h4>Timeline</h4>
  <%= render partial: 'shared/activities', locals: {activities: activities} %>
</div>

app/views/home/api_warnings.html.erb
<div class="page-heading">
  <h1>API Warnings</h1>
</div>

<h2>Generate new API Warnings</h2>
<div class="row">
<%= form_tag api_warnings_path, method: :get, builder: BootstrapForm do %>
  <div class="col-sm-4">
    <%= label_tag :start_date, "Orders last modified starting" %><br />
    <%= text_field_tag :start_date, "", class: 'js-datetimepicker form-control', required: true %>
  </div>
  <div class="col-sm-4">
    <%= label_tag :start_date, "Orders last modified ending" %><br />
    <%= text_field_tag :end_date, "",  class: 'js-datetimepicker form-control', required: true %>
  </div>
  <div class="col-sm-4">
    <%= hidden_field_tag :generate_api_warnings %>
    <%= submit_tag "Generate Warnings", class: 'btn btn-warning' %>
  </div>
<% end %>
</div>

<% if @api_warnings.empty? %>
  <div class="alert alert-success">
    <p>No orders appear to have any API issues at this time</p>
  </div>
<% else %>
<div class="row">
  <%= paginate @api_warnings %>

  <table class='table table-striped'>
    <thead>
      <tr>
        <% if Warning.column_names.include?("created_at") %>
          <th>Date Issued</th>
        <% end %>
        <th>Warnable</th>
        <th>Warnable ID</th>
        <th>Warning</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @api_warnings.each do |warning| %>
        <tr>
          <% if Warning.column_names.include?("created_at") %>
            <td><%= warning.created_at.strftime('%m/%d/%Y %I:%M%p') %></td>
          <% end %>
          <td><%= warning.warnable_type.underscore.humanize %></td>
          <td><%= warning.warnable_id %></td>
          <td><%= warning.message %></td>
          <td>

            <%= link_to "/warnings/#{warning.id}", data: { toggle: 'tooltip' }, class: 'btn btn-xs btn-success', title: 'Show' do %>
              <i class='glyphicon glyphicon-eye-open'></i>
            <% end %>
            <% begin %>
            <% unless warning.dismissed? %>
              <%= button_to_dismiss_warning warning, text: '<i class="glyphicon glyphicon-ok"></i>'.html_safe, data: { toggle: 'tooltip' }, class: 'btn btn-xs btn-primary', title: 'Dismiss' do %>
              <% end %>
            <% end %>
          <% rescue %>
          <% end %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @api_warnings %>
</div>
<% end %>

app/views/home/index.html.erb
<div class="page-heading">
  <h1>Dashboard For <%= @current_user.full_name %></h1>
</div>

<div class="col-sm-6">
  <div class="box-info">
    <h2>Rejected Artwork Requests</h2>
    <% if @rejected_artwork_requests.empty? %>
        <div class="alert alert-success">
          <p>
            <b>None of your Artwork Requests have been rejected</b>
            The art staff appreciates you!
          </p>
        </div>
    <% else %>
        <div class="alert alert-danger">
          <h3>You have artwork requests that have been rejected</h3>
        </div>
        <ul>
          <% @rejected_artwork_requests.each do |ar| %>
              <li><%= link_to ar.order.name, [edit_order_path(ar.order), "#artworks"].join %>
              </li>
          <% end %>
        </ul>
    <% end %>
  </div>
</div>

<div class="col-sm-6">
  <div class="box-info">
    <h2>Orders with Warnings</h2>
    <% if @order_warnings.empty? %>
        <div class="alert alert-success">
          <p><b>None of your orders have warnings</b>
            Pat yourself on the back, <%= @current_user.first_name %>!</p>
        </div>
    <% else %>
        <div class="alert alert-danger">
          <h3>You have orders with warnings that need to be addressed</h3>
        </div>
        <ul>
          <% @order_warnings.each do |o| %>
              <% if o.warnings_count == 0
                   Sunspot.index o
                   next
                 end %>
              <li><%= link_to "#{o.name} (#{pluralize(o.warnings_count, 'warning')})", order_warnings_path(o, active_only: 'true') %>
              </li>
          <% end %>
        </ul>
    <% end %>
  </div>
</div>

<% if current_user.is_in_sales? %>
    <div class="col-sm-12">
      <div class="box-info">
        <h2>Pending Quote Requests Assigned To You</h2>

        <div class="additional-btn">
          Show your quote requests: <%= filter_quote_requests(current_user) %>
        </div>
        <div id='quote-request-list' class="no-pagination">
          <% if @pending_quote_requests.empty? %>
              <div class=" alert alert-success">
                <p>You're all caught up on your quote requests! Now go and close on those quotes.</p>
              </div>
          <% else %>
              <%= render partial: 'quote_requests/table', locals: {quote_requests: quote_requests_for(current_user)} %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

<% if current_user.is_in_sales? && !Rails.env.test? %>
    <div class="col-sm-12">
      <div class="box-info">
        <h2>Sales Stats Dashboard</h2>

        <div class="additional-btn">
          <%= link_to 'https://www.periscopedata.com/shared/87e7708c-980a-4be9-98ab-317c2e1bcaa5',
                      target: '_new', class: 'additional-icon' do %>
              <i class="fa fa-dashboard"></i> Open In New Window
          <% end %>
        </div>
        <iframe id="ifm" src="https://www.periscopedata.com/shared/87e7708c-980a-4be9-98ab-317c2e1bcaa5?embed=true" style="height: 400px; width: 100%"></iframe>
      </div>
    </div>
<% end %>

app/views/home/not_allowed.html.erb
<div class="page-heading">
  <h1>Sorry!</h1>
</div>
<div class='box-info'>
  You're not allowed to view that page.
</div>