config/routes.rb
require 'sidekiq/web'

CrmSoftwearcrmCom::Application.routes.draw do
  mount ActsAsWarnable::Engine => '/'

  root 'home#index'
  get 'home/api_warnings', to: 'home#api_warnings', as: :api_warnings
  get 'home/not_allowed', to: 'home#not_allowed', as: :not_allowed

  get 'imprints/ink_colors', to: 'imprints#ink_colors', as: :imprint_ink_colors
  get 'imprints/new', to: 'imprints#new', as: :new_imprint
  get  'jobs/:job_id/imprints/from_quotes', to: 'imprints#from_quotes', as: :imprint_from_quotes
  post 'jobs/:job_id/imprints/from_quotes', to: 'imprints#create_from_quotes'

  resources :imprintables do
    collection do
      resources :brands, :colors
      resources :imprintable_groups
      post 'update_imprintable_variants'
      get 'costs', to: 'costs#mass_new'
      post 'costs', to: 'costs#mass_create'

      resources :sizes do
        collection do
          post 'update_size_order'
        end
      end
    end
  end

  resources :user_attributes, only: [:edit, :update]
  get '/set-session-token', to: 'users#set_session_token', as: :set_session_token
  get '/clear-user-query-cache', to: 'users#clear_query_cache', as: :clear_user_query_cache

  get 'tags/:tag', to: 'imprintables#index', as: :tag

  resources :brands, :colors, :costs
  resources :artworks do
    collection do
      get 'select'
    end
    member do
      get 'full_view'
    end
  end

  resources :artwork_requests do
    member do
      post 'transition(/:state_machine(/:transition))' => :state, as: :transition
    end
    collection do
      get 'tab/:tab' => :tab, as: :tab
    end
  end

  get 'proofing_manager_dashboard', to: 'artwork_requests#manager_dashboard', as: :proofing_manager_dashboard

  resources :prices, only: [:create, :new, :destroy, :index] do
    collection do
      get 'destroy_all'
    end
  end

  resources :quotes, shallow: true do
    member do
      put 'integrate', to: 'quotes#integrate'
    end
    resource :emails

    resources :comments

    collection do
      get 'quote_select'
      post 'stage_quote'
    end
  end
  post 'email/freshdesk', to: 'emails#freshdesk'
  resources :comments
  warning_paths_for :quotes, :orders

  resources :quote_requests do
    get :dock
    post :create_freshdesk_ticket
    resources :emails, :comments

    collection do
      post :filter
    end
  end
  warning_paths_for :quote_requests
  resources :warnings

  scope 'configuration' do
    resources :shipping_methods, :stores, :line_item_templates
    resources :imprint_methods do
      get '/print_locations', to: 'imprint_methods#print_locations', as: :print_locations
    end
    match 'integrated_crms', to: 'settings#edit', via: :get
    match 'update_integrated_crms', to: 'settings#update', via: :put
    resources :email_templates do
      get '/preview_body', to: 'email_templates#preview_body', as: :preview_body
      collection do
        # TODO: you'll need something like this if you want to expand templates to use more than just quotes
        get '/fetch_table_attributes/(:table_name)', to: 'email_templates#fetch_table_attributes'
      end
    end
    resources :platen_hoops
  end

  scope 'administration' do
    resources :coupons do
      collection { get '/validate/:code', to: 'coupons#validate', as: :validate_coupon }
    end
    resources :in_store_credits do
      collection { get :search }
    end
    resources :payment_drops, except: :destroy
    resources :deposits
  end

  get 'payments/undropped', to: 'payments#undropped'
  resources :payments, :shipments

  resources :orders do
    member do
      get 'tab/:tab' => :tab, as: :tab
      get 'production_dashboard', as: 'production_dashboard'
      get :imprintable_sheets, as: :imprintable_sheets
      get :order_report, as: :order_report
      get 'state/:state_machine' => :state,  as: :state
      get :check_cancelation
      post 'transition/(:state_machine/:transition)' => :state, as: :transition
      post :send_to_production
      post :clone
    end

    resources :comments

    collection do
      get 'fba'
      get 'new_fba'
      post 'fba_job_info'
    end

    get 'timeline', to: 'timeline#show', as: :timeline
    resources :payments, :discounts, shallow: true
    resources :artwork_requests
    resources :proofs do
      member do
        post 'transition/(:state_machine/:transition)' => :state, as: :transition
      end

      collection do
        get 'email_customer'
        post 'email_customer'
      end
    end

    resources :jobs, only: [:create, :update, :destroy, :show], shallow: true do
      resources :name_numbers, only: [:create, :destroy]
      member do
        get 'names_numbers', as: :name_number_csv_from
        put :duplicate
      end

      resources :line_items, except: [:update] do
        get :form_partial, on: :member
        post :update_sort_orders
      end
      resources :imprints, except: [:index]
    end
  end

  resources :fba_spreadsheet_uploads
  resources :fba_job_templates do
    collection do
      get :print_locations
    end
  end
  resources :fba_products do
    collection do
      get :variant_fields
      get :new_from_spreadsheet
      post :upload_spreadsheet
    end
  end

  post   'line_items', to: 'line_items#create'
  post   'jobs/:job_id/line_items/from_quotes', to: 'line_items#create_from_quotes', as: :line_items_from_quote
  get    'line_item/select_options', to: 'line_items#select_options'
  put    'line_items/update', to: 'line_items#update'
  patch  'line_items/update', to: 'line_items#update'

  put    'jobs/:job_id/imprints/update', to: 'imprints#update', as: :job_imprints_update
  patch  'jobs/:job_id/imprints/update', to: 'imprints#update'

  namespace 'search' do
    resources :queries
  end

  get '/search', to: 'search/queries#search', as: :search

  resources :sales_reports, only: [:index, :create]
  get '/sales_reports/:report_type/:start_time...:end_time(.:format)', to: 'sales_reports#show', as: :sales_reports_show

  namespace 'api', defaults: { format: :json } do
    match '*path', to: 'api#options', via: :options
    resources 'orders', only: [:index, :show, :update]
    resources 'jobs', only: [:index, :show, :update]
    resources 'imprints', only: [:index, :show, :update]
    resources 'imprintables'
    resources 'imprintable_variants', only: [:index, :show]
    resources 'colors'
    resources 'sizes'
    resources 'quote_requests', only: [:create, :index, :show]
    resources 'shipments', only: [:index, :show, :update]
  end

  mount Sidekiq::Web => '/sidekiq'

  get '/undock', to: 'home#undock'
  get '/undock/:quote_request_id', to: 'home#undock'

  post '/error-report', to: 'error_reports#email_report'

  namespace 'customer' do
    resources :orders, only: [:show, :edit, :update] do
      resources :payments, only: [:index, :new, :create] do
        collection do
          match 'paypal_express', via: [:get, :post]
          match 'paypal_express_success', via: [:get, :post]
        end
      end
    end
  end

  namespace 'crm' do
    resources :contacts
  end

end

app/models/shipping_method.rb
class ShippingMethod < ActiveRecord::Base
  FBA = 'UPS Amazon FBA'

  include Popularity

  acts_as_paranoid
  popularity_rated_from :shipments

  has_many :shipments
  
  validates :name, uniqueness: true, presence: true
  # TODO: custom validator?
  validates :tracking_url, format: { with: URI::regexp(%w(http https)), message: 'should be in format http://www.url.com/path' }
end

app/controllers/shipping_methods_controller.rb
class ShippingMethodsController < InheritedResources::Base
  before_filter :sales_manager_only, only: [:create, :update, :destroy, :edit]
  before_action :set_current_action

  def show
    super do |format|
      format.html { redirect_to edit_shipping_method_path params[:id] }
    end
  end

  def update
    super do |success, failure|
      success.html { redirect_to shipping_methods_path }
      failure.html { render action: :edit }
    end
  end

  protected

  def set_current_action
    @current_action = 'shipping_methods'
  end

  private

  def permitted_params
    params.permit(shipping_method: [:name, :tracking_url])
  end
end

app/views/shipping_methods/_form.html.erb
<div class="box-info">
 <%= render partial: 'shared/modal_errors', locals: {object: shipping_method} %>

  <%= form_for shipping_method do |f| %>
        <div id="horizontal-form" class="collapse in">
          <div class="form-group">
            <%= f.label :name, class: 'col-sm-2 control-label' %>

            <div class="col-sm-10">
              <% if shipping_method.errors.include?(:name) %>
                <% shipping_method.errors.full_messages_for(:name).each do |message| %>
                  <p class="text-danger"><%= message %></p>
                <% end %>
              <% end %>

              <%= f.text_field :name, class: 'form-control' %>

              <p class="help-block">The name of the shipping method (UPS Ground, for example)
             </div>
          </div>

          <div class="form-group">
            <%= f.label :tracking_url, class: 'col-sm-2 control-label' %>

            <div class="col-sm-10">
              <% if shipping_method.errors.include?(:tracking_url) %>
                <% shipping_method.errors.full_messages_for(:tracking_url).each do |message| %>
                  <p class="text-danger"><%= message %></p>
                <% end %>
              <% end %>

              <%= f.text_field :tracking_url, class: 'form-control' %>

              <p class="help-block">
                URL At which you can enter in a tracking number to track your shipment. 
                Enter :tracking_number for where the tracking number should be filled in. 
              </p>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-info"><%= create_or_edit_text(shipping_method) %> Shipping Method</button>
            </div>
          </div>
        </div>
  <% end %>
</div>

app/views/shipping_methods/_table.html.erb
<div class="box-info full">
  <div class="table-responsive">
    <table class="table table-hover" id="shipping_methods_list">
      <thead>
        <tr>
          <th>Name</th>
          <th>Tracking URL</th>
          <th>Popularity</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% shipping_methods.each do |shipping_method| %>
          <tr id="<%= model_table_row_id shipping_method %>">
            <td><%= shipping_method.name %></td>
            <td><%= link_to shipping_method.tracking_url, shipping_method.tracking_url, target: '_blank' %></td>
            <td>*<%= shipping_method.popularity %></td>
            <td>
              <div class="btn-group btn-group-xs">
                <%= link_to edit_shipping_method_path(shipping_method),
                            class: 'btn btn-default', 'data-action' => 'edit',
                            'data-toggle' => 'tooltip', 'title' => 'Edit' do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to shipping_method_path(shipping_method),
                            class: 'btn btn-default',
                            data: {confirm: 'Are you sure you would like to delete the shipping method?'},
                            method: :delete, 'data-action' => 'destroy',
                            'data-toggle' => 'tooltip', 'title' => 'Destroy' do %>
                  <i class="fa fa-times"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shipping_methods/edit.html.erb
<div class="page-heading animated fadeInDownBig">
  <h1>Shipping Methods <small>Edit shipping method <i><%= @shipping_method.name %></i></small></h1>
</div>

<div class="row full">
  <%= render partial: 'form', locals: { shipping_method: @shipping_method } %>
</div>

app/views/shipping_methods/index.html.erb
<div class="page-heading animated fadeInDownBig col-lg-9">
  <h1>Shipping Methods <small>Configure the shipping methods available for shipments</small></h1>
</div>

<div class="col-lg-3 text-right">
  <%= link_to 'Add a Shipping Method', new_shipping_method_path, class: 'btn btn-primary' %>
</div>

<div class="box-info row clear">
  <%= render partial: 'table', locals: { shipping_methods: @shipping_methods } %>
</div>

app/views/shipping_methods/new.html.erb
<div class="page-heading animated fadeInDownBig">
  <h1>Shipping Methods <small>Create a new shipping method</small></h1>
</div>

<div class="row full">
  <%= render partial: 'form', locals: { shipping_method: @shipping_method } %>
</div>